# Generated by Django 4.1.2 on 2022-10-24 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coolapp', '0002_film_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='comments',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
